apiVersion: v1	
kind: Service	
metadata:	
  name: organization-api-nonsql
spec:
  selector:
    app: organization-api-nonsql
  type: LoadBalancer
  ports:	
  - protocol: TCP
    port: 8080
    targetPort: 8080
